# Generated by Django 3.1.4 on 2020-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogauthorsorderable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCathegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=255, help_text='Slug to identify posts by this cathegory', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Blog CathegorY',
                'verbose_name_plural': 'Blog CathegoriesSs',
                'ordering': ['name'],
            },
        ),
    ]
