# Generated by Django 3.1.4 on 2020-12-27 20:25

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcathegory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='cathegories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCathegory'),
        ),
    ]
