# Generated by Django 3.1.4 on 2020-12-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'SubscriberssS', 'verbose_name_plural': 'SubscriIiberssS'},
        ),
    ]
